# Generated by Django 3.2.6 on 2021-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_dt', models.DateField(verbose_name='Check-out Date')),
                ('volume_nm', models.CharField(max_length=20, verbose_name='Tape Volume Name')),
                ('pool_nm', models.CharField(max_length=20, verbose_name='Pool Name')),
                ('cycle', models.IntegerField(default=14, verbose_name='Keep Cycle')),
                ('due_dt', models.DateField(verbose_name='Due Date')),
                ('safein_chk', models.CharField(default='X', max_length=20, verbose_name='Check in coffer')),
                ('safeout_chk', models.CharField(default='X', max_length=20, verbose_name='Check out coffer')),
            ],
            options={
                'verbose_name': 'Keep',
                'verbose_name_plural': 'keeps',
                'db_table': 'RemoteKeep',
                'ordering': ('-check_dt', 'pool_nm', 'volume_nm'),
            },
        ),
    ]
