# Generated by Django 3.2.6 on 2021-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keep',
            options={'ordering': ('-check_dt', '-pool_nm', 'volume_nm'), 'verbose_name': 'Keep', 'verbose_name_plural': 'keeps'},
        ),
        migrations.AddField(
            model_name='keep',
            name='safein_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Safe-in Date'),
        ),
        migrations.AddField(
            model_name='keep',
            name='safeout_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Safe-out Date'),
        ),
    ]
