# Generated by Django 3.2.6 on 2021-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote', '0002_auto_20211004_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keep',
            name='safein_chk',
            field=models.CharField(default='X', max_length=1, verbose_name='Check in coffer'),
        ),
        migrations.AlterField(
            model_name='keep',
            name='safeout_chk',
            field=models.CharField(default='X', max_length=1, verbose_name='Check out coffer'),
        ),
    ]
