# Generated by Django 3.2.6 on 2021-10-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote', '0004_auto_20211014_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keep',
            name='safeout_chk',
            field=models.CharField(choices=[('o', '출고확인'), ('x', '출고대기'), ('w', 'Withdrawn')], default='x', max_length=1, verbose_name='Check out coffer'),
        ),
    ]
