# Generated by Django 3.2.6 on 2021-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_dt', models.DateTimeField(verbose_name='Backup Date')),
                ('schedule_tm', models.CharField(max_length=20, verbose_name='Scheduled Time')),
                ('schedule_nm', models.CharField(max_length=50, verbose_name='Schedule Name')),
                ('nodename', models.CharField(max_length=50, verbose_name='Schedule Name')),
                ('domain_nm', models.CharField(max_length=50, verbose_name='Domain Name')),
                ('start_tm', models.CharField(max_length=20, verbose_name='Start Time')),
                ('end_tm', models.CharField(max_length=20, verbose_name='End Time')),
                ('taken', models.IntegerField(default=0, verbose_name='Taken Time')),
                ('status', models.CharField(max_length=20, verbose_name='Backup Result')),
                ('returncode', models.IntegerField(verbose_name='Return Code')),
                ('action', models.TextField(verbose_name='Action Content')),
                ('note', models.TextField(verbose_name='Note')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'logs',
                'db_table': 'EventLog',
                'ordering': ('domain_nm', 'schedule_tm'),
            },
        ),
    ]
