# Generated by Django 3.2.6 on 2021-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-backup_dt', 'domain_nm', 'schedule_tm'), 'verbose_name': 'Log', 'verbose_name_plural': 'logs'},
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.TextField(blank=True, null=True, verbose_name='Action Content'),
        ),
        migrations.AlterField(
            model_name='log',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='MODIFY DATE'),
        ),
        migrations.AlterField(
            model_name='log',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
