# Generated by Django 3.2.6 on 2021-09-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20210917_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='backup_dt',
            field=models.DateField(verbose_name='Backup Date'),
        ),
    ]
